---
title: "arbeidskrav"
format: html
editor: visual
---

# Analyse av pendlevaner og trafikkutvikling på Haugalandet

```{r}
library(tidyverse)
library(readr)
library(readxl)
library(dplyr)
library(stringr)
```

```{r}
ny_data <- read_excel("ny_data.xlsx")
tidligere_data <- read_excel("tidligere_data.xlsx")
```

```{r}
# Fjerne mellomrom og linjeskift fra kolonnenavnene i 'tidligere_data'
colnames(tidligere_data) <- str_trim(gsub("\r\n", "", colnames(tidligere_data)))

# Omdøpe variabler i 'tidligere_data' for å matche variablene i 'ny_data'
tidligere_data <- tidligere_data %>%
  rename(
    `Kjønn` = `Hvilket kjønn identifiserer du som?`,  # Omdøp "Hvilket kjønn identifiserer du som?" til "Kjønn"
    `Alder` = `Din alder`,  # Omdøp "Din alder" til "Alder"
    `Utdanning` = `Hva er din høyeste utdanning?`,  # Omdøp utdanning
    `Næring` = `I hvilken næring jobber du?`,  # Omdøp næring
    `Inntektsgruppe` = `Hvilken inntektsgruppe hører du til?`,  # Omdøp inntektsgruppe
    `Antall personer i husstanden` = `Hvor mange personer bor i din husstand?`,  # Omdøp antall personer
    `Antall med førerkort` = `Hvor mange i husstanden har førerkort?`,  # Omdøp førerkort
    `Transportmåte disponibelt` = `Hva har du til disposisjon?`,  # Omdøp transportmåte
    `Hvordan kommer du deg til jobb` = `Hva har du reist med siste uken?`,  # Omdøp hvordan du kommer deg til jobb
    `Tid brukt til jobb` = `Hvor lang er din pendletid til jobb?`,  # Omdøp tid brukt til jobb
    `Postnummer` = `Hva er ditt postnummer (bosted)`,  # Omdøp postnummer
    `Postnummer arbeidssted` = `Hva er ditt postnummer (arbeidsplass)`,  # Omdøp postnummer arbeidssted
    `Fast oppmøte` = `Har du fast oppmøtested?`,  # Omdøp fast oppmøte
    `Parkering ved jobb` = `Er det gode parkeringsmuligheter nær din arbeidsplass?`  # Omdøp parkering
  )

# Omdøpe variabler i 'ny_data' (hvis nødvendig) for å matche samme tema
ny_data <- ny_data %>%
  rename(
    `Kjønn` = `Hvilket kjønn identifiserer du deg som?`,  # Omdøp "Hvilket kjønn identifiserer du deg som?" til "Kjønn"
    `Alder` = `Hva er alderen din?`,  # Omdøp "Hva er alderen din?" til "Alder"
    `Utdanning` = `Hva er din høyeste utdanning?`,  # Omdøp utdanning
    `Næring` = `I hvilken næring jobber du?`,  # Omdøp næring
    `Inntektsgruppe` = `Hvilken inntektsgruppe tilhører du?`,  # Omdøp inntektsgruppe
    `Antall personer i husstanden` = `Hvor mange bor i din husstand?`,  # Omdøp antall personer
    `Antall med førerkort` = `Hvor mange har førerkort i din husstand?`,  # Omdøp førerkort
    `Transportmåte disponibelt` = `Hvilke muligheter har du tilgjengelig for reise til jobb?`,  # Omdøp transportmåte
    `Hvordan kommer du deg til jobb` = `Hvilke muligheter bruker du for å reise til jobb?`,  # Omdøp hvordan du kommer deg til jobb
    `Tid brukt til jobb` = `Hvor lang tid bruker du til jobb`,  # Omdøp tid brukt til jobb
    `Postnummer` = `Hvilket postnummer er din husstand plassert under?`,  # Omdøp postnummer
    `Postnummer arbeidssted` = `Hvilket postnummer er arbeidsplassen din plasser under?`,  # Omdøp postnummer arbeidssted
    `Fast oppmøte` = `Har du fast oppmøte til jobb?`,  # Omdøp fast oppmøte
    `Parkering ved jobb` = `Har du parkeringsmuligheter på jobb?`  # Omdøp parkering
  )
```

```{r}
# Velge felles variabler (tema) i begge datasettene
common_columns <- c("Starttidspunkt", "Kjønn", "Alder", "Utdanning", "Næring", "Inntektsgruppe",
                    "Antall personer i husstanden", "Antall med førerkort", "Transportmåte disponibelt",
                    "Hvordan kommer du deg til jobb", "Tid brukt til jobb", "Postnummer",
                    "Postnummer arbeidssted", "Fast oppmøte", "Parkering ved jobb")

# Slå sammen datasettene
merged_data <- bind_rows(
  select(ny_data, all_of(common_columns)),
  select(tidligere_data, all_of(common_columns))
)

# Se resultatet
head(merged_data)

# Sjekk at du har fått 160 observasjoner
nrow(merged_data)
```

## **1.0 Introduksjon**

## **2.0 Pendlevaner på Haugalandet**

### 2.1 Data

### 2.2 Modell for analyse av pendlevaner

### 2.3 Myndighetene og virkemiddel for valg av kjøretøy

### 2.4 Deskriptiv statistikk

### 2.5 Resultater

## **3.0 Trafikkutvikling på Haugalandet**

### 3.1 Data

### 3.2 Årsdøgntrafikk

### 3.3 Timetrafikk

### 3.4 Resultater

## **4.0 Konklusjon**

## **5.0 Referanser**
